apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sourcegraph
resources:
  - git::git@github.com:Deichindianer/deploy-sourcegraph/base?ref=native-kustomize
components:
  - git::git@github.com:Deichindianer/deploy-sourcegraph/components/non-privileged?ref=native-kustomize
  - git::git@github.com:Deichindianer/deploy-sourcegraph/components/non-privileged-create-cluster?ref=native-kustomize

